export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "About me",
  headline: "Andrei Duduman",
  description:
    "I recently completed my post graduate degree in computer science, where I gained a deep understanding of various computer science concepts and technologies. During my studies, I took courses in data structures, algorithms, computer networks, operating systems, and software engineering, among others. I also had the opportunity to work on several projects, including the development of a web application. My post graduate degree has equipped me with the knowledge and skills necessary to tackle a wide range of challenges in the field of computer science and has prepared me for a successful career in this industry.",
  buttonLabel: "Get started",
  imgStart: false,
  img: require("../../images/ProfileImage.jpeg"),
  alt: "Profile",
  dark: true,
  primary: true,
  darkText: false,
};
export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Unlimited Access",
  headline: "Unlimited Transactions zero fees",
  description: "Get access to our exclusive content",
  buttonLabel: "Learn More",
  imgStart: true,
  img: require("../../images/svg-2.svg").default,
  alt: "Image 2",
  dark: false,
  primary: false,
  darkText: true,
};
