export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium Bank",
  headline: "Unlimited Transactions zero fees",
  description: "Get access to our exclusive content",
  buttonLabel: "Get started",
  imgStart: false,
  img: require("../../images/svg-1.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};
export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "PUnlimited Access",
  headline: "Unlimited Transactions zero fees",
  description: "Get access to our exclusive content",
  buttonLabel: "Learn More",
  imgStart: true,
  img: require("../../images/svg-2.svg").default,
  alt: "Image 2",
  dark: false,
  primary: false,
  darkText: true,
};
